title: Argonauts Crew

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

plugins:
  - jekyll-assets

sass:
    sass_dir: _assets/sass
assets:
  destination: "/assets"
  compression: false
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  gzip: false
  sources:
    - node_modules
    - _assets/sass